#:schema node_modules/wrangler/config-schema.json

name = "aipipe"
main = "src/worker.js"
compatibility_date = "2025-04-15"

[[routes]]
pattern = "aipipe.org"
custom_domain = true

# Docs: https://developers.cloudflare.com/workers/static-assets/binding/
[assets]
directory = "./public"

# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[[durable_objects.bindings]]
name = "AIPIPE_COST"
class_name = "AIPipeCost"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "AIPipeCost" ]
